#!/bin/sh
#
# ifplugd    Monitors Ethernet link state and runs ifup/ifdown on changes.
#

DAEMON=/usr/sbin/ifplugd
INTERFACES="eth0"
PIDDIR=/run/ifplugd

[ -x "$DAEMON" ] || exit 0

start() {
	mkdir -p "$PIDDIR"
	for iface in $INTERFACES; do
		echo "Starting ifplugd for $iface..."
		"$DAEMON" -n -i "$iface" -r /etc/ifplugd/ifplugd.action &
		echo $! > "$PIDDIR/ifplugd.$iface.pid"
	done
}

stop() {
	for iface in $INTERFACES; do
		echo "Stopping ifplugd for $iface..."
		start-stop-daemon -K -p "$PIDDIR/ifplugd.$iface.pid" -o
		rm -f "$PIDDIR/ifplugd.$iface.pid"
	done
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)   start ;;
  stop)    stop ;;
  restart) restart ;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
